"""
SOMA Generic Execution Bridge — POW 1.

Calls ANY libc function from the discovered catalog.
The bridge has per-function signature setup (necessary for ctypes type safety)
but ZERO domain logic — it doesn't know what open() or read() MEAN.
It just sets up types and calls.

The catalog is data. The sequencing is neural. The bridge is plumbing.
"""

import ctypes
import os
from datetime import datetime, timezone

from pow.pow1.discovery import (
    CallingConvention, Dirent, StatResult, Utsname, Timeval,
    EMIT_ID, STOP_ID,
)


class ProgramStep:
    """One step in a program generated by the mind."""
    __slots__ = ("conv_id", "arg_types", "arg_values")

    def __init__(self, conv_id: int, arg_types: list, arg_values: list):
        self.conv_id = conv_id
        self.arg_types = arg_types
        self.arg_values = arg_values

    def format(self, step_idx: int, catalog: list) -> str:
        if self.conv_id == STOP_ID:
            return "STOP"
        if self.conv_id == EMIT_ID:
            ref = self.arg_values[0] if self.arg_values else "?"
            return f"${step_idx} = EMIT(${ref})"
        conv = catalog[self.conv_id]
        args = []
        for at, av in zip(self.arg_types, self.arg_values):
            if at == "span":
                args.append(f'"{av}"')
            elif at == "ref":
                args.append(f"${av}")
        return f"${step_idx} = libc.{conv.function}({', '.join(args)})"


# ============================================================================
# Per-function ctypes signature table.
# This is NOT a dispatch table — it contains no logic, no sequencing,
# no domain knowledge. It's type metadata, like a CPU knowing that
# register R0 is 32-bit and R1 is 64-bit.
# ============================================================================

def _setup_and_call(func_name, libc_funcs, conv, resolved_args):
    """Set up ctypes types and call. One entry per function signature.
    Contains NO domain logic — only type marshalling."""

    func = libc_funcs[func_name]

    if func_name == "open":
        path = _to_bytes(resolved_args[0])
        flags = conv.fixed_args.get("flags", 0)
        # 2-arg open (non-variadic, for O_RDONLY)
        func.argtypes = [ctypes.c_char_p, ctypes.c_int]
        func.restype = ctypes.c_int
        return func(path, flags)

    if func_name == "creat":
        path = _to_bytes(resolved_args[0])
        mode = conv.fixed_args.get("mode", 0o644)
        # creat() is non-variadic — works correctly on ARM64
        func.argtypes = [ctypes.c_char_p, ctypes.c_uint16]
        func.restype = ctypes.c_int
        return func(path, mode)

    if func_name == "close":
        func.argtypes = [ctypes.c_int]
        func.restype = ctypes.c_int
        return func(resolved_args[0])

    if func_name == "read":
        count = conv.fixed_args.get("count", 65536)
        buf = ctypes.create_string_buffer(count)
        func.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_size_t]
        func.restype = ctypes.c_ssize_t
        n = func(resolved_args[0], buf, count)
        return buf.raw[:max(n, 0)].decode("utf-8", errors="replace") if n > 0 else ""

    if func_name == "write":
        data = _to_bytes(resolved_args[1])
        func.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_size_t]
        func.restype = ctypes.c_ssize_t
        return func(resolved_args[0], data, len(data))

    if func_name == "opendir":
        func.argtypes = [ctypes.c_char_p]
        func.restype = ctypes.c_void_p
        return func(_to_bytes(resolved_args[0]))

    if func_name == "readdir":
        func.argtypes = [ctypes.c_void_p]
        func.restype = ctypes.POINTER(Dirent)
        entries = []
        while True:
            ptr = func(resolved_args[0])
            if not ptr:
                break
            name = ptr.contents.d_name.decode("utf-8", errors="replace")
            if name not in (".", ".."):
                entries.append(name)
        return sorted(entries)

    if func_name == "closedir":
        func.argtypes = [ctypes.c_void_p]
        func.restype = ctypes.c_int
        return func(resolved_args[0])

    if func_name == "unlink":
        func.argtypes = [ctypes.c_char_p]
        func.restype = ctypes.c_int
        return func(_to_bytes(resolved_args[0]))

    if func_name == "mkdir":
        mode = conv.fixed_args.get("mode", 0o755)
        func.argtypes = [ctypes.c_char_p, ctypes.c_uint16]
        func.restype = ctypes.c_int
        return func(_to_bytes(resolved_args[0]), mode)

    if func_name == "rename":
        func.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
        func.restype = ctypes.c_int
        return func(_to_bytes(resolved_args[0]), _to_bytes(resolved_args[1]))

    if func_name == "access":
        mode = conv.fixed_args.get("mode", 0)
        func.argtypes = [ctypes.c_char_p, ctypes.c_int]
        func.restype = ctypes.c_int
        return func(_to_bytes(resolved_args[0]), mode) == 0

    if func_name == "stat":
        buf = StatResult()
        func.argtypes = [ctypes.c_char_p, ctypes.POINTER(StatResult)]
        func.restype = ctypes.c_int
        rc = func(_to_bytes(resolved_args[0]), ctypes.byref(buf))
        if rc != 0:
            return None
        return {"size": buf.st_size,
                "modified": datetime.fromtimestamp(buf.st_mtimespec.tv_sec).isoformat(),
                "mode": oct(buf.st_mode)}

    if func_name == "getcwd":
        size = conv.fixed_args.get("size", 1024)
        buf = ctypes.create_string_buffer(size)
        func.argtypes = [ctypes.c_char_p, ctypes.c_size_t]
        func.restype = ctypes.c_char_p
        result = func(buf, size)
        return result.decode("utf-8") if result else None

    if func_name == "gettimeofday":
        tv = Timeval()
        func.argtypes = [ctypes.POINTER(Timeval), ctypes.c_void_p]
        func.restype = ctypes.c_int
        func(ctypes.byref(tv), None)
        return datetime.fromtimestamp(tv.tv_sec, tz=timezone.utc).isoformat()

    if func_name == "uname":
        buf = Utsname()
        func.argtypes = [ctypes.POINTER(Utsname)]
        func.restype = ctypes.c_int
        func(ctypes.byref(buf))
        return {"system": buf.sysname.decode(), "release": buf.release.decode(),
                "machine": buf.machine.decode()}

    return None


def _to_bytes(s):
    if isinstance(s, str):
        return s.encode("utf-8")
    return s


# ============================================================================
# The Generic Bridge
# ============================================================================

class GenericBridge:
    """Executes programs by calling libc through ctypes.
    No dispatch table. No domain logic. Just type marshalling and calling."""

    def __init__(self, catalog: list[CallingConvention], libc):
        self.catalog = catalog
        self.libc = libc
        self._funcs = {}
        for conv in catalog:
            if conv.function not in self._funcs:
                self._funcs[conv.function] = getattr(libc, conv.function)

    def execute_program(self, steps: list[ProgramStep], on_step=None) -> dict:
        """Execute a program. Resolve refs, call libc, collect results."""
        results = []
        output = None
        trace = []

        for i, step in enumerate(steps):
            if step.conv_id == STOP_ID:
                trace.append({"step": i, "op": "STOP", "ok": True})
                if on_step:
                    on_step(i, "STOP", "")
                break

            if step.conv_id == EMIT_ID:
                ref_idx = step.arg_values[0] if step.arg_values else 0
                if isinstance(ref_idx, int) and ref_idx < len(results):
                    output = results[ref_idx]
                trace.append({"step": i, "op": "EMIT", "ok": True})
                if on_step:
                    on_step(i, "EMIT", "")
                continue

            conv = self.catalog[step.conv_id]

            # Resolve arguments
            resolved = []
            for at, av in zip(step.arg_types, step.arg_values):
                if at == "ref":
                    if isinstance(av, int) and av < len(results):
                        resolved.append(results[av])
                    else:
                        self._cleanup(results)
                        return {"success": False, "output": None, "trace": trace,
                                "error": f"Step {i} (libc.{conv.function}): invalid ref ${av}"}
                elif at == "span":
                    resolved.append(os.path.expanduser(av) if av else "")

            try:
                result = _setup_and_call(conv.function, self._funcs, conv, resolved)
                results.append(result)

                summary = self._summarize(result)
                trace.append({"step": i, "op": f"libc.{conv.function}", "ok": True,
                              "summary": summary})
                if on_step:
                    on_step(i, f"libc.{conv.function}", summary)

            except Exception as e:
                if on_step:
                    on_step(i, f"libc.{conv.function}", f"ERROR: {e}")
                self._cleanup(results)
                return {"success": False, "output": None, "trace": trace,
                        "error": f"Step {i} (libc.{conv.function}): {e}"}

        return {"success": True, "output": output, "trace": trace, "error": None}

    def _cleanup(self, results):
        for r in results:
            if isinstance(r, int) and r > 2:
                try:
                    close_func = self._funcs.get("close")
                    if close_func:
                        close_func.argtypes = [ctypes.c_int]
                        close_func.restype = ctypes.c_int
                        close_func(r)
                except Exception:
                    pass

    def _summarize(self, result) -> str:
        if result is None:
            return ""
        if isinstance(result, bool):
            return "yes" if result else "no"
        if isinstance(result, int):
            return f"fd={result}" if result > 2 else str(result)
        if isinstance(result, str):
            return f"{len(result)} chars" if len(result) > 50 else result
        if isinstance(result, list):
            return f"{len(result)} entries"
        if isinstance(result, dict):
            return ", ".join(f"{k}={v}" for k, v in list(result.items())[:3])
        return type(result).__name__
