//! SOMA Mind — neural inference engine.
//!
//! The MindEngine trait defines the abstract interface.
//! OnnxMindEngine implements it for server/desktop targets.
//! EmbeddedMindEngine (future) will implement it for ESP32/MCU.

pub mod onnx_engine;
pub mod tokenizer;
pub mod lora;

use anyhow::Result;
use std::path::Path;

/// A program step generated by the mind.
#[derive(Debug, Clone)]
pub struct ProgramStep {
    pub conv_id: i32,
    pub arg0_type: ArgType,
    pub arg0_value: ArgValue,
    pub arg1_type: ArgType,
    pub arg1_value: ArgValue,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ArgType { None, Span, Ref }

#[derive(Debug, Clone)]
pub enum ArgValue {
    None,
    Span(String),
    Ref(usize),
}

/// A generated program — sequence of steps.
#[derive(Debug, Clone)]
pub struct Program {
    pub steps: Vec<ProgramStep>,
    pub confidence: f32,
}

/// Model metadata.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ModelMeta {
    pub vocab_size: usize,
    pub num_conventions: usize,
    pub max_steps: usize,
    pub max_seq_len: usize,
    pub decoder_dim: usize,
    pub emit_id: usize,
    pub stop_id: usize,
    pub start_token: usize,
    pub catalog: Vec<CatalogEntry>,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct CatalogEntry {
    pub id: usize,
    pub name: String,
    pub function: String,
    pub call_pattern: String,
    pub var_args: Vec<VarArg>,
    pub description: String,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct VarArg {
    pub name: String,
    #[serde(rename = "type")]
    pub arg_type: String,
}

pub const EMIT_ID: i32 = -1;
pub const STOP_ID: i32 = -2;

/// Mind info for proprioception.
#[derive(Debug, Clone)]
pub struct MindInfo {
    pub backend: String,
    pub param_count: usize,
    pub conventions_known: usize,
    pub max_steps: usize,
    pub lora_layers: usize,
    pub lora_magnitude: f32,
}

/// Abstract MindEngine trait (Whitepaper Section 4.2).
/// Two backends: OnnxMindEngine (server) and EmbeddedMindEngine (ESP32).
pub trait MindEngine: Send + Sync {
    /// Run inference: intent text -> program
    fn infer(&self, text: &str) -> Result<Program>;

    /// Get model metadata
    fn meta(&self) -> &ModelMeta;

    /// Get mind info for proprioception
    fn info(&self) -> MindInfo;
}

impl ProgramStep {
    pub fn format(&self, step_idx: usize, catalog: &[CatalogEntry]) -> String {
        if self.conv_id == STOP_ID { return "STOP".to_string(); }
        if self.conv_id == EMIT_ID {
            let r = match &self.arg0_value {
                ArgValue::Ref(r) => format!("${}", r),
                _ => "?".to_string(),
            };
            return format!("${} = EMIT({})", step_idx, r);
        }
        if let Some(conv) = catalog.get(self.conv_id as usize) {
            let mut args = Vec::new();
            for val in [&self.arg0_value, &self.arg1_value] {
                match val {
                    ArgValue::Span(s) => args.push(format!("\"{}\"", s)),
                    ArgValue::Ref(r) => args.push(format!("${}", r)),
                    ArgValue::None => {}
                }
            }
            format!("${} = libc.{}({})", step_idx, conv.function, args.join(", "))
        } else {
            format!("${} = conv:{}(?)", step_idx, self.conv_id)
        }
    }
}
