//! SOMA Mind — neural inference engine.
//!
//! The MindEngine trait defines the abstract interface.
//! OnnxMindEngine implements it for server/desktop targets.
//! EmbeddedMindEngine (future) will implement it for ESP32/MCU.

pub mod adaptation;
pub mod onnx_engine;
pub mod tokenizer;
pub mod lora;

use anyhow::Result;

/// Configuration for MindEngine initialization (Section 4.2).
#[derive(Debug, Clone)]
pub struct MindConfig {
    pub max_program_steps: usize,
    pub temperature: f32,
    pub max_inference_time_secs: u64,
}

// Future: InferenceContext per-request struct (Section 12.2).
// Explicit context with encoder_output, decoder_hidden, program_steps.
// Currently implicit (variables on stack in infer()).

/// A program step generated by the mind.
#[derive(Debug, Clone, PartialEq)]
pub struct ProgramStep {
    pub conv_id: i32,
    pub arg0_type: ArgType,
    pub arg0_value: ArgValue,
    pub arg1_type: ArgType,
    pub arg1_value: ArgValue,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ArgType { None, Span, Ref, Literal }

#[derive(Debug, Clone, PartialEq)]
pub enum ArgValue {
    None,
    Span(String),
    Ref(usize),
    Literal(String),
}

/// A generated program — sequence of steps.
#[derive(Debug, Clone)]
pub struct Program {
    pub steps: Vec<ProgramStep>,
    pub confidence: f32,
    /// Cached (hidden_state, base_opcode_logits) per decoder step for fast LoRA adaptation.
    /// Pre-computed during inference so adaptation doesn't need to re-run the ONNX model.
    pub cached_states: Vec<(Vec<f32>, Vec<f32>)>,
}

/// Model metadata.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ModelMeta {
    pub vocab_size: usize,
    pub num_conventions: usize,
    pub max_steps: usize,
    #[serde(default = "default_max_seq_len")]
    pub max_seq_len: usize,
    pub decoder_dim: usize,
    pub emit_id: usize,
    pub stop_id: usize,
    pub start_token: usize,
    /// Convention catalog — may be embedded in meta.json or loaded from catalog.json
    #[serde(default)]
    pub catalog: Vec<CatalogEntry>,
}

fn default_max_seq_len() -> usize { 20 }

#[derive(Debug, Clone, serde::Deserialize)]
pub struct CatalogEntry {
    pub id: usize,
    pub name: String,
    pub function: String,
    pub call_pattern: String,
    pub var_args: Vec<VarArg>,
    pub description: String,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct VarArg {
    pub name: String,
    #[serde(rename = "type")]
    pub arg_type: String,
}

pub const EMIT_ID: i32 = -1;
pub const STOP_ID: i32 = -2;

/// Mind info for proprioception.
#[derive(Debug, Clone)]
pub struct MindInfo {
    pub backend: String,
    pub param_count: usize,
    pub conventions_known: usize,
    pub max_steps: usize,
    pub lora_layers: usize,
    pub lora_magnitude: f32,
}

/// Abstract MindEngine trait (Whitepaper Section 4.2).
///
/// Dual-backend architecture: OnnxMindEngine runs on server/desktop
/// targets using the ONNX Runtime, while EmbeddedMindEngine (future)
/// will target ESP32/MCU hardware. Both backends share this trait so
/// the rest of SOMA (Cortex, Body, etc.) is backend-agnostic.
///
/// # Load Pattern
/// Initialization uses associated functions (e.g., `OnnxMindEngine::load(path)`)
/// rather than a trait method, because each backend returns its own concrete type.
/// A factory function or enum dispatch can be used for runtime backend selection.
pub trait MindEngine: Send + Sync {
    /// Run full inference: intent text → program steps.
    /// Note: Spec 4.2 shows `infer(tokens, length)` but we take raw text
    /// because tokenization is internal to the engine — the engine owns
    /// the tokenizer and handles encoding. This preserves encapsulation
    /// and prevents callers from needing tokenizer access.
    fn infer(&self, text: &str) -> Result<Program>;

    /// Get model metadata
    fn meta(&self) -> &ModelMeta;

    /// Get mind info for proprioception
    fn info(&self) -> MindInfo;

    /// Attach a LoRA adapter by name with the given weights.
    fn attach_lora(&mut self, _name: &str, _weights: &crate::mind::lora::LoRAWeights) -> Result<()> { Ok(()) }

    /// Attach LoRA layers from serialized bytes (plugin LoRA, Section 7.3).
    /// The bytes are expected to be a JSON-serialized `LoRABundle`.
    fn attach_lora_bytes(&mut self, _plugin_name: &str, _data: &[u8]) -> Result<()> { Ok(()) }

    /// Detach (remove) a LoRA adapter by name without merging.
    fn detach_lora(&mut self, _name: &str) -> Result<()> { Ok(()) }

    /// Merge a LoRA adapter's weights permanently into the base model.
    fn merge_lora(&mut self, _name: &str) -> Result<()> { Ok(()) }

    /// Checkpoint the current LoRA state for serialization.
    fn checkpoint_lora(&self) -> Result<crate::mind::lora::LoRACheckpoint> {
        Ok(crate::mind::lora::LoRACheckpoint { layers: vec![], adaptation_count: 0, experience_count: 0 })
    }

    /// Restore LoRA state from a checkpoint.
    fn restore_lora(&mut self, _checkpoint: &crate::mind::lora::LoRACheckpoint) -> Result<()> { Ok(()) }
}

impl ProgramStep {
    pub fn format(&self, step_idx: usize, catalog: &[CatalogEntry]) -> String {
        if self.conv_id == STOP_ID { return "STOP".to_string(); }
        if self.conv_id == EMIT_ID {
            let r = match &self.arg0_value {
                ArgValue::Ref(r) => format!("${}", r),
                _ => "?".to_string(),
            };
            return format!("${} = EMIT({})", step_idx, r);
        }
        if let Some(conv) = catalog.get(self.conv_id as usize) {
            let mut args = Vec::new();
            for val in [&self.arg0_value, &self.arg1_value] {
                match val {
                    ArgValue::Span(s) => args.push(format!("\"{}\"", s)),
                    ArgValue::Ref(r) => args.push(format!("${}", r)),
                    ArgValue::Literal(s) => args.push(format!("'{}'", s)),
                    ArgValue::None => {}
                }
            }
            format!("${} = libc.{}({})", step_idx, conv.function, args.join(", "))
        } else {
            format!("${} = conv:{}(?)", step_idx, self.conv_id)
        }
    }
}
