//! Neural inference engine that converts natural language intents into executable programs.
//!
//! The Mind is a `BiLSTM` encoder + GRU decoder neural network. It takes an intent string
//! (e.g. "list files in /tmp"), runs ONNX inference to produce a `Program` -- a sequence
//! of `ProgramStep`s that reference plugin conventions by ID. Each step also resolves
//! arguments via span extraction (pointing into the input text), step references, or
//! literal generation.
//!
//! The `MindEngine` trait abstracts the inference backend. `OnnxMindEngine` (via tract)
//! is the production implementation; `EmbeddedMindEngine` is a future target for MCU
//! hardware.

pub mod adaptation;
pub mod onnx_engine;
pub mod tokenizer;
pub mod lora;

use anyhow::Result;

/// Configuration for `MindEngine` initialization.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct MindConfig {
    pub max_program_steps: usize,
    /// Softmax temperature for opcode selection. Lower values produce more deterministic programs.
    pub temperature: f32,
    pub max_inference_time_secs: u64,
}

/// A single step in a generated program. Maps to one plugin convention call.
///
/// `conv_id` is the convention index (offset by `plugin_idx * 1000` for catalog plugins),
/// or a sentinel: `EMIT_ID` (-1) to return a value, `STOP_ID` (-2) to end the program.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProgramStep {
    pub conv_id: i32,
    pub arg0_type: ArgType,
    pub arg0_value: ArgValue,
    pub arg1_type: ArgType,
    pub arg1_value: ArgValue,
}

/// How a step argument is sourced.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArgType { None, Span, Ref, Literal }

/// Resolved argument value for a program step.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ArgValue {
    None,
    /// Text extracted from the input intent via span pointers.
    Span(String),
    /// Reference to the output of a prior step (by step index).
    Ref(usize),
    /// A literal value generated by the decoder's vocabulary head.
    Literal(String),
}

/// The output of `MindEngine::infer()` -- an executable sequence of convention calls.
#[derive(Debug, Clone)]
pub struct Program {
    pub steps: Vec<ProgramStep>,
    /// Minimum softmax probability across all decoded steps (conservative estimate).
    pub confidence: f32,
    /// Per-step (`hidden_state`, `base_opcode_logits`) cached during inference.
    /// Enables `LoRA` adaptation without re-running the ONNX model.
    pub cached_states: Vec<(Vec<f32>, Vec<f32>)>,
}

/// Model metadata loaded from `meta.json`. Defines the architecture dimensions
/// and special token IDs that the inference loop depends on.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ModelMeta {
    pub vocab_size: usize,
    /// Number of convention opcodes the model was trained on.
    pub num_conventions: usize,
    /// Maximum decoder steps per program.
    pub max_steps: usize,
    /// Maximum input sequence length (tokens). Inputs are padded/truncated to this.
    #[serde(default = "default_max_seq_len")]
    pub max_seq_len: usize,
    /// Hidden dimension shared by encoder output and decoder state.
    pub decoder_dim: usize,
    pub emit_id: usize,
    pub stop_id: usize,
    /// Token ID fed to the decoder at step 0 (before any prediction).
    pub start_token: usize,
    /// Convention catalog -- may be embedded in meta.json or loaded from catalog.json.
    #[serde(default)]
    pub catalog: Vec<CatalogEntry>,
}

const fn default_max_seq_len() -> usize { 20 }

/// A known convention that the model can emit as an opcode.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct CatalogEntry {
    pub id: usize,
    pub name: String,
    /// The function name used for display (e.g. "stat", "readdir").
    pub function: String,
    #[allow(dead_code)]
    pub call_pattern: String,
    #[allow(dead_code)]
    pub var_args: Vec<VarArg>,
    #[allow(dead_code)]
    pub description: String,
}

/// Typed argument descriptor within a `CatalogEntry`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct VarArg {
    #[allow(dead_code)]
    pub name: String,
    #[serde(rename = "type")]
    #[allow(dead_code)]
    pub arg_type: String,
}

/// Sentinel `conv_id` indicating the step returns a value from a prior step.
pub const EMIT_ID: i32 = -1;
/// Sentinel `conv_id` indicating the program is complete.
pub const STOP_ID: i32 = -2;

/// Self-description of the Mind for the proprioception subsystem.
#[derive(Debug, Clone)]
pub struct MindInfo {
    pub backend: String,
    /// Estimated total parameter count across encoder + decoder.
    #[allow(dead_code)]
    pub param_count: usize,
    pub conventions_known: usize,
    pub max_steps: usize,
    /// Number of active `LoRA` adapter layers.
    pub lora_layers: usize,
    /// Sum of `LoRA` magnitudes across all active layers; tracks adaptation drift.
    pub lora_magnitude: f32,
}

/// Abstract inference backend.
///
/// Takes `&str` rather than pre-tokenized input because tokenization is an
/// internal concern of the engine -- the engine owns the tokenizer. This
/// preserves encapsulation and avoids exposing tokenizer details to callers.
///
/// Loading is via associated functions (e.g. `OnnxMindEngine::load(path)`)
/// rather than a trait method, since each backend returns its own concrete type.
pub trait MindEngine: Send + Sync {
    /// Run inference: natural language intent to executable program.
    fn infer(&self, text: &str) -> Result<Program>;

    fn meta(&self) -> &ModelMeta;

    fn info(&self) -> MindInfo;

    /// Attach a `LoRA` adapter layer for a named output head.
    fn attach_lora(&mut self, _name: &str, _weights: &crate::mind::lora::LoRAWeights) -> Result<()> { Ok(()) }

    /// Attach `LoRA` layers from a JSON-serialized `LoRABundle` (plugin-provided weights).
    fn attach_lora_bytes(&mut self, _plugin_name: &str, _data: &[u8]) -> Result<()> { Ok(()) }

    /// Remove a `LoRA` adapter without merging its weights into the base model.
    #[allow(dead_code)]
    fn detach_lora(&mut self, _name: &str) -> Result<()> { Ok(()) }

    /// Permanently fold a `LoRA` adapter's weight delta into the base model.
    #[allow(dead_code)]
    fn merge_lora(&mut self, _name: &str) -> Result<()> { Ok(()) }

    /// Snapshot current `LoRA` state for checkpoint serialization.
    fn checkpoint_lora(&self) -> Result<crate::mind::lora::LoRACheckpoint> {
        Ok(crate::mind::lora::LoRACheckpoint { layers: vec![], adaptation_count: 0, experience_count: 0 })
    }

    /// Restore `LoRA` state from a previously saved checkpoint.
    fn restore_lora(&mut self, _checkpoint: &crate::mind::lora::LoRACheckpoint) -> Result<()> { Ok(()) }
}

impl ProgramStep {
    /// Render this step as a human-readable string (e.g. `$0 = libc.stat("/tmp")`).
    #[allow(clippy::option_if_let_else)] // if-let is clearer with internal mutation
    pub fn format(&self, step_idx: usize, catalog: &[CatalogEntry]) -> String {
        if self.conv_id == STOP_ID { return "STOP".to_string(); }
        if self.conv_id == EMIT_ID {
            let r = match &self.arg0_value {
                ArgValue::Ref(r) => format!("${r}"),
                _ => "?".to_string(),
            };
            return format!("${step_idx} = EMIT({r})");
        }
        #[allow(clippy::cast_sign_loss)] // conv_id is non-negative here (STOP/EMIT handled above)
        if let Some(conv) = catalog.get(self.conv_id as usize) {
            let mut args = Vec::new();
            for val in [&self.arg0_value, &self.arg1_value] {
                match val {
                    ArgValue::Span(s) => args.push(format!("\"{s}\"")),
                    ArgValue::Ref(r) => args.push(format!("${r}")),
                    ArgValue::Literal(s) => args.push(format!("'{s}'")),
                    ArgValue::None => {}
                }
            }
            format!("${} = libc.{}({})", step_idx, conv.function, args.join(", "))
        } else {
            format!("${} = conv:{}(?)", step_idx, self.conv_id)
        }
    }
}
