CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE documents (
    id          SERIAL PRIMARY KEY,
    title       TEXT NOT NULL,
    content     TEXT NOT NULL,
    category    TEXT NOT NULL,
    tags        TEXT[] DEFAULT '{}',
    embedding   vector(128),
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_documents_category ON documents(category);
CREATE INDEX idx_documents_embedding ON documents USING ivfflat (embedding vector_cosine_ops) WITH (lists = 4);
CREATE INDEX idx_documents_fts ON documents USING gin (to_tsvector('english', title || ' ' || content));

-- Engineering documents
INSERT INTO documents (title, content, category, tags) VALUES
('API Rate Limiting Policy', 'All API endpoints enforce rate limiting. Default: 1000 requests per minute per API key. Burst: 50 requests per second. Exceeded limits return HTTP 429. Rate limit headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset. Enterprise tier: 10000 rpm. Contact platform team for custom limits.', 'engineering', '{api,rate-limit,infrastructure}'),
('Database Migration Guide', 'Migrations use Flyway. Naming: V{version}__{description}.sql. All migrations must be backwards-compatible for 2 releases. Destructive changes (DROP COLUMN, DROP TABLE) require a 3-phase migration: deprecate, stop-reading, remove. Run migrations: flyway -configFiles=conf/flyway.conf migrate. Rollback: flyway undo (last migration only).', 'engineering', '{database,migration,flyway}'),
('Microservice Communication Standards', 'Inter-service communication uses gRPC for synchronous calls, Kafka for async events. Service discovery via Consul. Circuit breaker: Hystrix with 5s timeout, 50% error threshold. Retry policy: exponential backoff, max 3 retries. All services must register health endpoints at /health and /ready.', 'engineering', '{microservices,grpc,kafka}'),
('Deployment Runbook', 'Deployments use ArgoCD with GitOps. Staging auto-deploys on merge to main. Production requires manual approval in ArgoCD UI. Canary rollout: 10% traffic for 15 minutes, then 50%, then 100%. Rollback: revert the Git commit, ArgoCD auto-syncs. Hotfix: branch from release tag, cherry-pick fix, deploy via expedited approval.', 'engineering', '{deployment,argocd,gitops}'),
('Observability Stack', 'Metrics: Prometheus + Grafana. Logs: Loki with structured JSON logging. Traces: OpenTelemetry + Jaeger. SLOs defined in Sloth. Alert routing: PagerDuty for P1/P2, Slack #alerts for P3/P4. Dashboard naming: team-service-aspect (e.g., platform-api-latency). Log retention: 30 days hot, 90 days cold in S3.', 'engineering', '{observability,prometheus,grafana,logging}'),
('Authentication Architecture', 'OAuth 2.0 + OIDC via Keycloak. Access tokens: JWT, 15min TTL. Refresh tokens: opaque, 7-day TTL, rotation on use. Service-to-service: mTLS with SPIFFE IDs. API keys: SHA-256 hashed, stored in Vault. Session management: Redis-backed, 30min idle timeout. MFA required for admin roles.', 'engineering', '{auth,oauth,keycloak,security}'),
('Data Pipeline Architecture', 'Ingestion: Kafka Connect from PostgreSQL CDC. Processing: Apache Flink for real-time, Spark for batch. Storage: Delta Lake on S3. Catalog: Apache Hive Metastore. Schema registry: Confluent Schema Registry with Avro. Data quality: Great Expectations checks on every pipeline run. SLA: end-to-end latency under 5 minutes for real-time, under 4 hours for batch.', 'engineering', '{data,pipeline,kafka,spark}'),

-- Legal/Compliance documents
('Data Retention Policy', 'Customer data retention periods: personal data 3 years after account closure (GDPR Art. 17). Financial records 7 years (SOX). Audit logs 5 years. Session data 90 days. Anonymized analytics: indefinite. EU customer data must reside in EU data centers (Frankfurt, Dublin). Right to erasure requests: 30-day SLA. Data classification: Public, Internal, Confidential, Restricted.', 'legal', '{data-retention,gdpr,compliance}'),
('GDPR Compliance Framework', 'Data processing lawful bases: consent, contract, legitimate interest. DPIA required for high-risk processing. Data Protection Officer: legal@company.com. Breach notification: 72 hours to supervisory authority. Privacy by design: all new features require privacy impact assessment. Cross-border transfers: Standard Contractual Clauses for non-EU processors.', 'legal', '{gdpr,privacy,compliance}'),
('SOC 2 Type II Controls', 'Annual SOC 2 Type II audit covers: security, availability, processing integrity, confidentiality. Key controls: access reviews quarterly, vulnerability scans weekly, penetration tests annually, change management via Jira tickets, incident response tested semi-annually. Evidence collection: Drata automated evidence. Audit period: January 1 to December 31.', 'legal', '{soc2,audit,compliance}'),
('Acceptable Use Policy', 'Company systems for business purposes only. No unauthorized software installation. No sharing of credentials. Report security incidents within 1 hour to security@company.com. Personal device usage requires MDM enrollment. VPN required for remote access to internal systems. Violations may result in disciplinary action up to termination.', 'legal', '{policy,acceptable-use,security}'),
('Vendor Risk Assessment', 'All vendors processing company data require risk assessment. Tier 1 (critical): annual on-site audit + SOC 2 report. Tier 2 (significant): questionnaire + SOC 2 report. Tier 3 (low): self-assessment questionnaire. Contract requirements: data processing agreement, breach notification clause, right to audit, data deletion on termination. Approved vendor list maintained in ServiceNow.', 'legal', '{vendor,risk,compliance}'),
('Intellectual Property Policy', 'All work product created during employment is company IP. Open source contributions require approval from legal. Patent disclosures submitted via IP portal. Non-compete: 12 months post-employment for direct competitors. NDA required for all contractors. Code scanning for license compliance: FOSSA on every build.', 'legal', '{ip,patent,legal}'),

-- HR documents
('Employee Benefits Overview', 'Health insurance: PPO and HDHP options, company covers 85% of premium. Dental and vision included. 401(k): 4% company match, immediate vesting. PTO: 20 days/year plus 10 company holidays. Parental leave: 16 weeks paid. Learning budget: $2,500/year for courses, conferences, books. Home office stipend: $1,000 one-time setup, $100/month ongoing.', 'hr', '{benefits,insurance,pto}'),
('Performance Review Process', 'Reviews twice annually: mid-year (June) and year-end (December). Self-assessment due 2 weeks before review date. Manager assessment uses competency framework: technical excellence, collaboration, leadership, impact. Rating scale: Exceeds, Meets, Developing, Below. Compensation adjustments in January based on year-end review. Promotion nominations in Q4.', 'hr', '{performance,review,compensation}'),
('Remote Work Policy', 'Hybrid model: minimum 2 days/week in office for local employees. Fully remote available for roles marked remote-eligible. Core hours: 10am-3pm local time for meetings. Equipment: company-provided laptop, monitor, keyboard. Internet reimbursement: $75/month. Co-working space: $300/month budget where available. International remote work: max 30 days/year, requires tax team approval.', 'hr', '{remote,hybrid,policy}'),
('Onboarding Checklist', 'Day 1: laptop setup, badge, Okta enrollment, Slack intro. Week 1: team introductions, architecture overview, dev environment setup, first PR. Month 1: complete security training, ship first feature, 1:1 with skip-level. Month 3: 90-day review with manager. Buddy assigned for first 90 days. Onboarding feedback survey at 30/60/90 days.', 'hr', '{onboarding,new-hire,checklist}'),
('Expense Policy', 'Pre-approval required for expenses over $500. Travel: economy class flights, hotels up to $250/night. Meals: $75/day while traveling. Client entertainment: $150/person with VP approval. Receipt required for all expenses over $25. Submit within 30 days. Reimbursement via Expensify, processed bi-weekly. Corporate card for recurring expenses over $200/month.', 'hr', '{expense,travel,reimbursement}'),

-- Finance documents
('Q4 Budget Summary', 'Total Q4 budget: $12.4M. Engineering: $5.2M (42%). Sales & Marketing: $3.1M (25%). G&A: $2.5M (20%). R&D: $1.6M (13%). Headcount: 187 FTE, 23 contractors. Cloud infrastructure: $890K/month (AWS $650K, GCP $180K, misc $60K). Burn rate: $4.1M/month. Runway: 18 months at current rate.', 'finance', '{budget,q4,financials}'),
('Procurement Process', 'Software purchases under $10K: manager approval. $10K-$50K: VP approval + procurement review. Over $50K: C-suite approval + legal review + security assessment. Preferred vendors: AWS, Google Cloud, Datadog, PagerDuty, Confluent. New vendor onboarding: 2-4 weeks for security review. Contract terms: annual preferred, multi-year for 15%+ discount. Payment: NET 30 standard.', 'finance', '{procurement,purchasing,vendors}'),
('Revenue Recognition Policy', 'ASC 606 five-step model. SaaS subscriptions: recognized ratably over subscription period. Professional services: recognized as delivered (time and materials) or percentage of completion (fixed price). Usage-based: recognized monthly based on actual consumption. Annual upfront payments: deferred revenue, recognized monthly. Multi-element arrangements: allocate based on standalone selling prices.', 'finance', '{revenue,asc606,accounting}'),
('Cloud Cost Optimization Report', 'Current monthly cloud spend: $890K. Top 3 cost drivers: compute (45%), storage (25%), data transfer (15%). Recommendations: reserved instances for stable workloads (projected savings: $180K/year), S3 lifecycle policies for cold data ($45K/year), right-sizing oversized instances ($95K/year). Total projected annual savings: $320K. Implementation timeline: 6 weeks.', 'finance', '{cloud,cost,optimization}');
