//! Plugin Manager — loads plugins, routes program steps to the right plugin.

use super::interface::{Convention, PluginError, SomaPlugin, Value};
use crate::mind::engine::{ArgValue, ProgramStep, EMIT_ID, STOP_ID};

/// Result of executing a full program.
pub struct ProgramResult {
    pub success: bool,
    pub output: Option<Value>,
    pub trace: Vec<TraceEntry>,
    pub error: Option<String>,
}

pub struct TraceEntry {
    pub step: usize,
    pub op: String,
    pub success: bool,
    pub summary: String,
}

pub struct PluginManager {
    plugins: Vec<Box<dyn SomaPlugin>>,
    /// Maps convention ID (from catalog) → (plugin_index, plugin_convention_id)
    routing: std::collections::HashMap<u32, (usize, u32)>,
}

impl PluginManager {
    pub fn new() -> Self {
        Self {
            plugins: Vec::new(),
            routing: std::collections::HashMap::new(),
        }
    }

    pub fn register(&mut self, plugin: Box<dyn SomaPlugin>) {
        let plugin_idx = self.plugins.len();
        let conventions = plugin.conventions();
        for conv in &conventions {
            self.routing.insert(conv.id, (plugin_idx, conv.id));
        }
        tracing::info!(
            plugin = plugin.name(),
            conventions = conventions.len(),
            "Plugin registered"
        );
        self.plugins.push(plugin);
    }

    /// Execute a single step by routing to the correct plugin.
    fn execute_step(&self, conv_id: u32, args: Vec<Value>) -> Result<Value, PluginError> {
        let (plugin_idx, plugin_conv_id) = self.routing.get(&conv_id)
            .ok_or_else(|| PluginError::NotFound(
                format!("No plugin for convention {}", conv_id)))?;
        self.plugins[*plugin_idx].execute(*plugin_conv_id, args)
    }

    /// Execute a full program generated by the mind.
    pub fn execute_program(&self, steps: &[ProgramStep]) -> ProgramResult {
        let mut results: Vec<Value> = Vec::new();
        let mut output: Option<Value> = None;
        let mut trace = Vec::new();

        for (i, step) in steps.iter().enumerate() {
            if step.conv_id == STOP_ID {
                trace.push(TraceEntry {
                    step: i, op: "STOP".into(), success: true, summary: String::new(),
                });
                break;
            }

            if step.conv_id == EMIT_ID {
                if let ArgValue::Ref(r) = &step.arg0_value {
                    if *r < results.len() {
                        output = Some(results[*r].clone());
                    }
                }
                trace.push(TraceEntry {
                    step: i, op: "EMIT".into(), success: true, summary: String::new(),
                });
                continue;
            }

            // Resolve arguments
            let mut resolved = Vec::new();
            for (atype, aval) in [
                (&step.arg0_type, &step.arg0_value),
                (&step.arg1_type, &step.arg1_value),
            ] {
                match aval {
                    ArgValue::Span(s) => {
                        // Expand ~ in paths
                        let expanded = if s.starts_with('~') {
                            shellexpand::tilde(s).to_string()
                        } else {
                            s.clone()
                        };
                        resolved.push(Value::String(expanded));
                    }
                    ArgValue::Ref(r) => {
                        if *r < results.len() {
                            resolved.push(results[*r].clone());
                        } else {
                            let err = format!("Step {} invalid ref ${}", i, r);
                            trace.push(TraceEntry {
                                step: i, op: "?".into(), success: false, summary: err.clone(),
                            });
                            return ProgramResult {
                                success: false, output: None, trace, error: Some(err),
                            };
                        }
                    }
                    ArgValue::None => {}
                }
            }

            match self.execute_step(step.conv_id as u32, resolved) {
                Ok(result) => {
                    let summary = format!("{}", &result);
                    trace.push(TraceEntry {
                        step: i,
                        op: format!("conv:{}", step.conv_id),
                        success: true,
                        summary,
                    });
                    results.push(result);
                }
                Err(e) => {
                    let err = format!("Step {}: {}", i, e);
                    trace.push(TraceEntry {
                        step: i,
                        op: format!("conv:{}", step.conv_id),
                        success: false,
                        summary: err.clone(),
                    });
                    // Cleanup open handles
                    for r in &results {
                        if let Value::Handle(h) = r {
                            unsafe { libc::close(*h as i32); }
                        }
                    }
                    return ProgramResult {
                        success: false, output: None, trace, error: Some(err),
                    };
                }
            }
        }

        ProgramResult { success: true, output, trace, error: None }
    }

    pub fn conventions(&self) -> Vec<Convention> {
        self.plugins.iter().flat_map(|p| p.conventions()).collect()
    }
}

// shellexpand for ~ paths
mod shellexpand {
    pub fn tilde(path: &str) -> String {
        if let Some(rest) = path.strip_prefix("~/") {
            if let Ok(home) = std::env::var("HOME") {
                return format!("{}/{}", home, rest);
            }
        }
        if path == "~" {
            if let Ok(home) = std::env::var("HOME") {
                return home;
            }
        }
        path.to_string()
    }
}
